import type {
  Difficulty,
  ExamId,
  PaperId,
  QuestionTypeId,
  SectionType,
  SubjectId,
  TestModeId,
} from './core'

export interface SectionConfig {
  id: string
  type: SectionType
  subject?: SubjectId
  /** Question ids assigned to this section */
  questionIds: string[]
  marksPerCorrect: number
  marksPerWrong: number
  marksPerUnattempted: number
  /** For multiple correct: partial credit scheme */
  partialScheme?: 'all-or-nothing' | 'proportional'
  durationSeconds: number
}

export interface TestConfig {
  id: string
  name: string
  mode: TestModeId
  exam: ExamId
  paper?: PaperId
  sections: SectionConfig[]
  totalQuestions: number
  durationSeconds: number
  negativeMarking: boolean
  shuffleQuestions: boolean
  shuffleOptions: boolean
  allowPause: boolean
  autoSubmit: boolean
  /** Optional time warning thresholds (seconds remaining) */
  warnings: number[]
  /** true if generated by adaptive engine */
  isAdaptive?: boolean
  createdAt: string
}

export interface AnsweredOption {
  questionId: string
  sectionId: string
  /** For single: selected option index. For multiple: selected indices */
  selected: number[]
  /** For matrix/match: row -> col mapping */
  matrix?: Record<number, number>
  markedForReview: boolean
  /** timestamp ms */
  answeredAt?: number
  isGuessed?: boolean
  timeSpent: number
  visited: boolean
}

export type QuestionResult = 'correct' | 'wrong' | 'partial' | 'unattempted' | 'not-visited'

export interface QuestionPerformance {
  questionId: string
  sectionId: string
  result: QuestionResult
  awardedMarks: number
  maxMarks: number
  selected: number[]
  matrix?: Record<number, number>
  correctIndices: number[]
  timeSpent: number
  estimatedTime: number
  isGuessed: boolean
  markedForReview: boolean
  visited: boolean
  subject: SubjectId
  chapter: string
  microTopic: string
  difficulty: Difficulty
  type: QuestionTypeId
  year: number
  exam: ExamId
  isBookmarked: boolean
}

export interface TestResult {
  id: string
  configId: string
  startedAt: string
  submittedAt: string
  autoSubmitted: boolean
  sections: SectionConfig[]
  performance: QuestionPerformance[]
  scores: Record<string, number>
  sectionWise: Record<
    string,
    {
      correct: number
      wrong: number
      unattempted: number
      partial: number
      marks: number
      maxMarks: number
      accuracy: number
      timeSpent: number
    }
  >
  totalMarks: number
  maxMarks: number
  accuracy: number
  attemptRate: number
  totalTimeSpent: number
  guessedCorrect: number
  guessedWrong: number
  totalGuesses: number
  speed: number
}

export interface TestDraft {
  id: string
  config: TestConfig
  answers: Record<string, AnsweredOption>
  currentSectionId: string
  currentQuestionIndex: number
  timeRemaining: number
  lastSavedAt: string
  startedAt: string
  sectionsAnsweredCount: Record<string, number>
}
